# -*- coding: utf-8 -*-
"""ocr_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14sCu4EBjuiXShtZOthnGS2CfjFG2Vmco
"""

import cv2
import pytesseract

# Set Tesseract path (update this based on your system)
pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

def preprocess_image(image_path):
    image = cv2.imread(image_path)
    if image is None:
        print("Error: Could not load image. Check the file path")
        return None

    # Resize image
    image = cv2.resize(image, None, fx=2.1, fy=2.1, interpolation=cv2.INTER_LINEAR)

    # Convert to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Reduce noise (Denoising)
    gray = cv2.fastNlMeansDenoising(gray, h=10)

    # Apply adaptive thresholding
    thresh = cv2.adaptiveThreshold(
        gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2
    )

    return thresh

def extract_text(image_path):
    image = preprocess_image(image_path)
    if image is None:
        return ""  # Return empty string if image fails to load

    # Use Tesseract to extract text
    text = pytesseract.image_to_string(image, config="--psm 11 --oem 1")
    return text