version: "3.8"

services:
  app:
    build: .
    restart: always  # Ensures app restarts if it crashes
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: "postgresql://user:password@postgres:5432/trustid"
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the entire project directory for development
    command: ["python", "main.py"]  # Replace with your application's startup command

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trustid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: